# Generated by Django 2.1.2 on 2019-03-27 17:41

from django.db import migrations, models
import nt_core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatResource',
            fields=[
                ('id', models.CharField(default=uuid.UUID('27d15d92-5d29-4975-9998-4c4810eaca9d'), editable=False, max_length=40, primary_key=True, serialize=False)),
                ('create_time', models.BigIntegerField(default=nt_core.models.get_current_time_bigint)),
                ('update_time', models.BigIntegerField(default=nt_core.models.get_current_time_bigint)),
                ('appid', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('request_count', models.IntegerField(blank=True, null=True)),
                ('fail_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_resource',
            },
        ),
    ]
