# Generated by Django 2.1.2 on 2019-03-26 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nt_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbackmessage',
            name='id',
            field=models.CharField(default=uuid.UUID('e8b37b64-d36e-488a-ad34-12ebffd1865f'), editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
