# Generated by Django 2.1.2 on 2019-03-28 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nt_user', '0004_auto_20190328_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbackmessage',
            name='id',
            field=models.CharField(default=uuid.UUID('8cd076d3-32cc-4398-b511-3af8575906d6'), editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
